# Generated by Django 4.1.5 on 2023-01-25 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('phone_no', models.CharField(max_length=255, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('stage 1', 'stage 1'), ('stage 2', 'stage 2'), ('stage 3', 'stage 3'), ('stage 4', 'stage 4'), ('stage 5', 'stage 5'), ('stage 6', 'stage 6'), ('stage 7', 'stage 7'), ('stage 8', 'stage 8'), ('stage 9', 'stage 9'), ('stage 10', 'stage 10'), ('stage 11', 'stage 11'), ('stage 12', 'stage 12'), ('stage 13', 'stage 13'), ('stage 14', 'stage 14'), ('stage 15', 'stage 15'), ('stage 16', 'stage 16')], max_length=68)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('current_level', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport1', models.FileField(upload_to=tracker.models.upload_doc)),
                ('passport2', models.FileField(upload_to=tracker.models.upload_doc)),
                ('application_form', models.FileField(upload_to=tracker.models.upload_doc)),
                ('proof_of_payment', models.FileField(upload_to=tracker.models.upload_doc)),
                ('deed_of_agreement', models.FileField(upload_to=tracker.models.upload_doc)),
                ('confirmation_letter', models.FileField(upload_to=tracker.models.upload_doc)),
                ('court_for_affidavit', models.FileField(upload_to=tracker.models.upload_doc)),
                ('risk_clearance', models.FileField(upload_to=tracker.models.upload_doc)),
                ('declaration_of_age', models.FileField(upload_to=tracker.models.upload_doc)),
                ('final_survey', models.FileField(upload_to=tracker.models.upload_doc)),
                ('site_analysis', models.FileField(upload_to=tracker.models.upload_doc)),
                ('environment_impact', models.FileField(upload_to=tracker.models.upload_doc)),
                ('valuation_report', models.FileField(upload_to=tracker.models.upload_doc)),
                ('recommendation', models.FileField(upload_to=tracker.models.upload_doc)),
                ('C_of_O', models.FileField(upload_to=tracker.models.upload_doc)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
