# Generated by Django 4.1.5 on 2023-01-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_user_is_active_user_is_staff_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
