# Generated by Django 4.1.5 on 2023-01-26 11:03

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_form',
        ),
        migrations.RemoveField(
            model_name='application',
            name='confirmation_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='court_for_affidavit',
        ),
        migrations.RemoveField(
            model_name='application',
            name='declaration_of_age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='deed_of_agreement',
        ),
        migrations.RemoveField(
            model_name='application',
            name='environment_impact',
        ),
        migrations.RemoveField(
            model_name='application',
            name='final_survey',
        ),
        migrations.RemoveField(
            model_name='application',
            name='level',
        ),
        migrations.RemoveField(
            model_name='application',
            name='passport1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='passport2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='proof_of_payment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='risk_clearance',
        ),
        migrations.RemoveField(
            model_name='application',
            name='site_analysis',
        ),
        migrations.RemoveField(
            model_name='application',
            name='valuation_report',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(default='FUT', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='agent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='birth_certificate',
            field=models.FileField(default='image.jpg', upload_to=tracker.models.upload_doc),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='block_no',
            field=models.CharField(default=234, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='business_reg_cert',
            field=models.FileField(default='reg.jpg', upload_to=tracker.models.upload_doc),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='business_reg_name',
            field=models.CharField(default='dami', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='business_reg_num',
            field=models.IntegerField(default=2345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='business_reg_year',
            field=models.IntegerField(default=234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='development_proposal',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.upload_doc),
        ),
        migrations.AddField(
            model_name='application',
            name='minning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(default='nigerian', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='occupation',
            field=models.CharField(default='student', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='plot_no',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='post_held',
            field=models.CharField(default='student', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='purpose_of_land',
            field=models.CharField(choices=[('INDUSTRY', 'INDUSTRY'), ('COMMERCIAL', 'COMMERCIAL'), ('HOUSING ESTATE', 'HOUSING ESTATE')], default='housing', max_length=68),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='specific_purpose_of_land',
            field=models.TextField(default='house'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='state_of_origin',
            field=models.CharField(default='osun', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='street_no',
            field=models.CharField(default=345, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='underdeveloped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='use',
            field=models.CharField(default='house', max_length=255),
            preserve_default=False,
        ),
    ]
