# Generated by Django 4.1.5 on 2023-01-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_application_level_application_site_lga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='business_reg_num',
            field=models.CharField(max_length=255),
        ),
    ]
