# Generated by Django 4.1.5 on 2023-01-27 08:08

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_application_business_reg_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='C_of_O',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.upload_doc),
        ),
    ]
