# Generated by Django 4.1.5 on 2023-01-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_application_c_of_o'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='upated_needed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
