# Generated by Django 4.1.5 on 2023-01-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_level_upated_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reg_num',
        ),
        migrations.AddField(
            model_name='application',
            name='reg_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
