# Generated by Django 4.1.5 on 2023-01-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_customer_reg_num_application_reg_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='upated_needed',
            new_name='updated_needed',
        ),
    ]
