# Generated by Django 4.1.5 on 2023-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_upated_needed_level_updated_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
